### Mohammed Abunada
### EDA

#### 1. Imports

In [5]:
import pandas as pd
import numpy as np
import plotly.express as px

#### 2. Data Loading

In [11]:
# I read the java, python & pharo train files
# using pd.read_parquet into 3 different pandas files

java = pd.read_parquet("data/java_train-00000-of-00001.parquet")
python = pd.read_parquet("data/python_train-00000-of-00001.parquet")
pharo = pd.read_parquet("data/pharo_train-00000-of-00001.parquet")

In [12]:
java.shape

(7614, 6)

In [13]:
python.shape

(1884, 6)

In [14]:
pharo.shape

(1298, 6)

#### 3. Feature Imbalance

In [25]:
java['labels']

0       [1, 0, 0, 0, 0, 0, 0]
1       [0, 0, 1, 0, 0, 0, 0]
2       [1, 0, 0, 0, 0, 0, 0]
3       [0, 0, 1, 0, 0, 0, 0]
4       [0, 0, 1, 0, 0, 0, 0]
                ...          
7609    [1, 0, 0, 0, 0, 0, 0]
7610    [1, 0, 0, 0, 0, 0, 0]
7611    [1, 0, 0, 0, 0, 0, 0]
7612    [1, 0, 0, 0, 0, 0, 0]
7613    [1, 0, 0, 0, 0, 0, 0]
Name: labels, Length: 7614, dtype: object

In [26]:
# Convert labels into a 2d numpy array
java_labels_arr = np.array(java['labels'].values.tolist())

In [27]:
java_labels_arr

array([[1, 0, 0, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       ...,
       [1, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [28]:
# Get the total counts of java
java_labels_arr.sum(axis=0)

array([3610,  267,  509, 2093,  904,  117,  311], dtype=int64)

In [29]:
java_labels = ['summary', 'Ownership', 'Expand', 'usage', 'Pointer', 'deprecation', 'rational']

In [33]:
perc = java_labels_arr.sum(axis=0) / java_labels_arr.sum()

In [78]:
colorscale = ['#1E4D2B', '#335D3F', '#486D53', '#5E7D66', '#738D7A', '#889D8E', '#9DADA2', '#B3BDB5', '#C8CDC9', '#DDDDDD'][::-1]

colorsclae = [(i/9, col) for i,col in enumerate(colorscale)]

In [79]:
# Plot distribution chart found in paper
fig = px.bar(x = java_labels, color=perc, y=perc, text=[str(i)+"%" for i in (perc*100).round(2)], template='plotly_white', color_continuous_scale=colorscale)
fig.update_layout(yaxis=dict(tickformat='%', title='Distribution'), xaxis=dict(title='Class'), title="Java Class Imbalance")

In [82]:
perc

array([0.28195122, 0.27902439, 0.10243902, 0.16731707, 0.16926829])

In [83]:
# Convert labels into a 2d numpy array
python_labels_arr = np.array(python['labels'].values.tolist())

python_labels_arr

# Get the total counts of python
python_labels_arr.sum(axis=0)

python_labels = ['Usage', 'Parameters', 'DevelopmentNotes', 'Expand', 'Summary']

perc = python_labels_arr.sum(axis=0) / python_labels_arr.sum()

# Plot distribution chart found in paper
fig = px.bar(x = python_labels, y= perc, color=perc, text=[str(i)+"%" for i in (perc*100).round(2)], template='plotly_white', color_continuous_scale=colorscale)
fig.update_layout(yaxis=dict(tickformat='%', title='Distribution'), xaxis=dict(title='Class'), title="Python Class Imbalance")